### ISSUE TITLE
Unable to call ABI methods whose logic requires foreignApps on the app call

### ISSUE THREAD

**Issue by codinronan** [algorandfoundation/algokit-utils-ts#87]
I'd simply like confirmation that what I'm seeing is correct, and that my apparent solution is also the required one:

* I have an ABI app with an application.json spec that I'm using. One of these methods is a read-only method designed to return a piece of information about the app that is near impossible to calculate outside of it.
* I construct an appClient: 
```
    const algokitClient = algokit.getAppClient({
      id: appId,
      resolveBy: 'id',
      sender,
      app: appSpec,
    }, client.algod);
```
* I call: `return algokitClient.call({ method: 'reader_method', methodArgs: [] );`

The call fails because the required foreign apps are not provided. There is no available way to include them in an ABI method call.

After reading through the source, it appears the reason for this is that the AtomicTransactionComposer call to the `addMethodCall` builder [here](https://github.com/algorandfoundation/algokit-utils-ts/blob/main/src/app.ts#L343) and its utility call to [getAppArgsForABICall](https://github.com/algorandfoundation/algokit-utils-ts/blob/main/src/app.ts#L588) are explicitly excluding the possibility of the `senderParams` including `appForeignApps` or `foreignApps`. The object returned by `getAppArgsForABICall` uses named properties which are then spread into the `addMethodCall` object, and these properties do not include ~15 or so named properties that `addMethodCall` can accept, including foreignApps and foreignAssets.

Is this design intentional? I cannot find anything in the ABI specification that indicates that read-only ABI method calls cannot include foreign apps. Due to blockchain limitations we have no choice but to use a network of apps to split responsibilities between the apps, so these references are required.

So my apparent solution then is simply not to use algokit to make these calls and execute bare `NoOp` simple application calls using algosdk directly using my own `AtomicTransactionComposer.addMethodCall`. Is this correct? Keeping in mind the apps themselves are both built in and deployed with Algokit, so they comply with its specifications.

What I don't understand is that the Python algokit library DOES support specifying foreign apps in a method call, so this appears to have been overlooked in the Typescript library.

**Comment by aorumbayev** [comment]
@codinronan thank you for reporting the issue, we need to evaluate some options on the right way to address this, you can see a related PR in progress at https://github.com/algorandfoundation/algokit-utils-ts/pull/91. 

Relaying some of the team's replies on your questions:
- The ts utils package was by design created to rely on typing to only expose functionality that is valid (for example it does not let you pass create params from non create calls and etc). 
- Regarding foreign refs, the original thinking for not allowing them was due to the fact that you can pass them in as abi parameters. Once we figure out a clear way to distinguish the interfaces of abi vs non abi calls in ts utils, this shall be addressed as part of that. We will keep you informed once this is addressed 👍

**Comment by codinronan** [comment]
> 

Great thanks for the confirmation, I appreciate the reply :) Will keep an eye out for what you guys come up with. Thanks!

**Comment by codinronan** [comment]
Beautiful, thank you! Now I can re-unify my code, always love red!
